version: "3"

services:
  db:
    image: postgres
    container_name: agroBovDb
    restart: always

    environment:
      POSTGRES_PASSWORD: r0Ot@369
      POSTGRES_USER: postgres
      POSTGRES_DB: agrobovdb

    ports:
      - 5432:5432

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

