version: '3.1'

services:
  db:
    ports:
      - 5432:5432
  
  api:
    build:
      context: .
      target: development
    
    ports:
      - 3030:3030
    
    volumes:
      - .:/usr/app:rw
      - /usr/app/node_modules
      
    command: npm run start:dev