version: '3.1'


services:
  db:
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 14038:5432

  api: 
    volumes:
      - app:/usr/app:ro
    ports:
      - 3030:3030
    command:  npm run start

volumes:
  dbdata:
  app: