version: "3"

services:
  db:
    image: postgres
    container_name: agroBovDb
    restart: always

    environment:
      POSTGRES_PASSWORD: r0Ot@369
      POSTGRES_USER: postgres
      POSTGRES_DB: agrobovDB

    ports:
      - 5432:5432

    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: agrobov-api
    ports:
      - 3030:3030

    volumes:
      - .:/usr/etc/app

    depends_on:
      - db

volumes:
  pgdata:

