version: "3.1"

services:
  db:
    image: postgres
    container_name: agroBovDb
    restart: always

    environment:
      POSTGRES_PASSWORD: r0Ot@369
      POSTGRES_DB: agrobovdb

    ports:
      - 5432:5432

    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: agrobovapi

    ports:
      - 3030:3030
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:r0Ot@369@db:5432/agrobovdb?schema=public
    links:
      - db

    command: "npm start"

volumes:
  pgdata:

