version: "3.1"

services:
  db:
    image: postgres
    container_name: agrobovdb
    restart: always

    environment:
      POSTGRES_PASSWORD: r0Ot@369
      POSTGRES_DB: agrobovdb

    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    container_name: agrobovapi
    restart: always
    expose:
      - 3030
    ports:
      - 3030:3030

    env_file:
      - .env
    depends_on:
      - db
    
    links:
      - db


volumes:
  pgdata:

